
DROP TABLE IF EXISTS Passwords;
DROP TABLE IF EXISTS People_Identifications;
DROP TABLE IF EXISTS Identifications;
DROP TABLE IF EXISTS Permissions;
DROP TABLE IF EXISTS Systems;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Dependants;
DROP TABLE IF EXISTS BasePeople;
DROP TABLE IF EXISTS People;


